name: Go
on: push
env:
  GO111MODULE: on
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Go ${{ matrix.go }}
    strategy:
      matrix:
        go:
        - '1.11'
        - '1.12'
        - '1.13'
        - '1.14'
        - '1.15'
        - '1.16'
        - '1.17'
        - '1.18'
        - '1.19'
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - run: go test -race ./...
